# Generated by Django 2.1 on 2018-08-18 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_rescuecamp_total_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuecamp',
            name='excess',
            field=models.TextField(blank=True, null=True, verbose_name='Excess - അധികമുള്ളത്'),
        ),
        migrations.AddField(
            model_name='rescuecamp',
            name='need',
            field=models.TextField(blank=True, null=True, verbose_name='Need - ആവശ്യമുണ്ട്'),
        ),
    ]
